{{- if .Values.postgresExporter.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: postgres-exporter-secret
  namespace: monitoring
  labels:
    {{- include "monitoring-exporters.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range .Values.postgresExporter.postgres.pods }}
  datasource-{{ .name }}: "postgresql://{{ $.Values.postgresExporter.postgres.username }}:{{ $.Values.postgresExporter.postgres.password }}@{{ .host }}:{{ .port }}/{{ $.Values.postgresExporter.postgres.database }}?sslmode={{ $.Values.postgresExporter.postgres.sslmode }}"
  {{- end }}
{{- end }}
---
{{- if .Values.redisExporter.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: redis-exporter-secret
  namespace: monitoring
  labels:
    {{- include "monitoring-exporters.labels" . | nindent 4 }}
type: Opaque
stringData:
  redis-password: {{ .Values.redisExporter.redis.password | quote }}
{{- end }}
---
{{- if .Values.pgpoolExporter.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: pgpool-exporter-secret
  namespace: monitoring
  labels:
    {{- include "monitoring-exporters.labels" . | nindent 4 }}
type: Opaque
stringData:
  datasource: "postgresql://{{ .Values.pgpoolExporter.pgpool.username }}:{{ .Values.pgpoolExporter.pgpool.password }}@{{ .Values.pgpoolExporter.pgpool.host }}:{{ .Values.pgpoolExporter.pgpool.port }}/{{ .Values.pgpoolExporter.pgpool.database }}?sslmode={{ .Values.pgpoolExporter.pgpool.sslmode }}"
{{- end }}
